name: GraalVM CE CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@8bbfe44ef9c6f5c07e5af036a1bffd561c037d18
        with:
          graalvm-version: 20.3.0.java11
      - name: Install Native Image
        run: gu install native-image
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Chmod
        run: chmod -R a+x ./mvnw
      - name: Build and push docker image
        env:
          DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        run: |
          DOCKER_IMAGE=`echo "${DOCKER_REGISTRY_URL}/${DOCKER_ORGANIZATION}/micronaut-demo0" | sed -e 's#//#/#' -e 's#^/##'`
          ./mvnw deploy -Dpackaging=docker-native -Djib.docker.image=$DOCKER_IMAGE
